# Generated by Django 3.1.4 on 2021-02-22 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Felhasznalo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('felhasznalonev', models.CharField(max_length=255)),
                ('jelszo', models.CharField(max_length=255)),
                ('szuldatum', models.DateField()),
                ('magassag', models.IntegerField()),
                ('suly_akt', models.IntegerField()),
                ('suly_cel', models.IntegerField()),
                ('ferfi', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='MozgasTipus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nev', models.CharField(max_length=255)),
                ('orankent', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Mozgas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum', models.DateTimeField()),
                ('ido', models.IntegerField()),
                ('felhasznalo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='koxapp.felhasznalo')),
                ('tipus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='koxapp.mozgastipus')),
            ],
        ),
        migrations.CreateModel(
            name='Bevitel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum', models.DateTimeField()),
                ('kaloria', models.IntegerField()),
                ('zsir', models.IntegerField()),
                ('feherje', models.IntegerField()),
                ('szenhidrat', models.IntegerField()),
                ('felhasznalo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='koxapp.felhasznalo')),
            ],
        ),
    ]
