# Generated by Django 3.1.4 on 2021-02-24 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('koxapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Etel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nev', models.CharField(max_length=255)),
                ('zsir', models.IntegerField()),
                ('feherje', models.IntegerField()),
                ('szenhidrat', models.IntegerField()),
            ],
        ),
    ]
