# Generated by Django 3.1.4 on 2021-02-24 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('koxapp', '0002_etel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='felhasznalo',
            name='felhasznalonev',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
